site_name: Compressive Framework (CF)
site_url: https://mamaofthree579-ship-it.github.io/compressive-framework-cf/
site_description: Documentation for the Compressive Framework (CF) project.
repo_name: mamaofthree579-ship-it/compressive-framework-cf
repo_url: https://github.com/mamaofthree579-ship-it/compressive-framework-cf

nav:
  - Home: index.md
  - Notebooks: notebooks.md
  - API Reference: api.md

theme:
  name: material
  features:
    - navigation.expand
    - navigation.sections
    - content.code.copy

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true
