site_name: Compressive Framework (CF)
site_description: Open scientific modeling of compressive particle behavior
site_author: mamaofthree579-ship-it
repo_url: https://github.com/mamaofthree579-ship-it/compressive-framework-cf
theme:
  name: material
  palette:
    primary: indigo
    accent: teal
  features:
    - navigation.tabs
    - navigation.top
    - search.highlight
    - search.suggest
    - content.code.copy
nav:
  - Home: index.md
  - Research:
      - Overview: research.md
      - Architecture: architecture.md
  - Simulations: simulations.md
markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.highlight
  - toc:
      permalink: true
plugins:
  - search
