site_name: Compressive Framework (CF)
site_description: Theoretical Gravitation & Particle Studies — compressive geometry & particle-field behavior.
site_author: mamaofthree579-ship-it
repo_url: https://github.com/mamaofthree579-ship-it/compressive-framework-cf

theme:
  name: material
  logo: images/cf-trifractal-dark.svg
  favicon: images/cf-trifractal-dark.svg
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: teal
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: teal
  features:
    - navigation.instant
    - navigation.tabs
    - content.code.copy

nav:
  - Home: index.md
  - Theory:
      - Overview: theory/overview.md
      - Equations: theory/equations.md
  - Simulations:
      - Interactive: simulation.md
      - Reference Plots: reference_plots.md
  - Notebooks:
      - Intro: notebooks/intro_to_cf.md
  - Contribute: contributing.md
  - Version: version.md

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      inline_syntax: ['$', '$']
      block_syntax: ['$$', '$$']
  - pymdownx.superfences
  - pymdownx.highlight

extra_css:
  - stylesheets/extra.css
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js

plugins:
  - search
  - git-revision-date-localized
