name: Deploy MkDocs

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Documentation Tools
        run: |
          pip install mkdocs-material \
                     mkdocs-git-revision-date-localized-plugin \
                     mkdocs-tags-plugin \
                     pymdown-extensions

      - name: Deploy to GitHub Pages
        run: |
          mkdocs gh-deploy --force
