site_name: Compressive Framework (CF)
site_description: A research framework for understanding compressive gravity and particle behavior
site_author: mamaofthree579-ship-it
repo_url: https://github.com/mamaofthree579-ship-it/compressive-framework-cf
repo_name: compressive-framework-cf

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top
    - search.highlight
    - search.suggest
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: pink
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: pink

nav:
  - Home: index.md
  - Theory:
      - Overview: theory/overview.md
      - Equations: theory/equations.md
  - Simulations:
      - Black Hole Model: simulations/bh_model.md
  - Notebooks:
      - Introduction: notebooks/intro_to_cf.md

markdown_extensions:
  - attr_list
  - toc:
      permalink: true
  - footnotes
  - codehilite
  - admonition

plugins:
  - search
