site_name: Compressive Framework (CF)
site_url: https://mamaofthree579-ship-it.github.io/compressive-framework-cf/

theme:
  name: material

nav:
  - Home: docs/index.md
  - Theory:
      - Overview: theory/overview.md
      - Equations: theory/equations.md
  - Simulations:
      - Concepts: simulation_concepts.md
      - Simulation Index: simulations.md
  - API Reference: api.md
  - Architecture: Architecture.md
  - Glossary: glossary.md
  - Contributor Guide: contributing.md
  - Research: research.md
  - Math Reference: math_reference.md
  - Reference Plots: reference_plots.md
  - Jupyter Notebooks:
      - Intro to CF: notebooks/intro_to_cf.md
