site_name: Compressive Framework (CF)
site_url: https://mamaofthree579-ship-it.github.io/compressive-framework-cf/
repo_url: https://github.com/mamaofthree579-ship-it/compressive-framework-cf
repo_name: mamaofthree579-ship-it/compressive-framework-cf

theme:
  name: material
  features:
    - navigation.expand
    - search.highlight
    - search.share

nav:
  - Home: index.md
  - Architecture: architecture.md
  - Math Reference: math_reference.md
  - Tutorials:
      - Introduction: tutorials/intro_to_cf.md
      - Equation Explorer: tutorials/equation_explorer.md
  - Glossary: glossary.md
  - Contributing: contributing.md

markdown_extensions:
  - toc:
      permalink: true
  - tables
  - footnotes
  - admonition
  - codehilite

plugins:
  - search
  - mkdocs-git-revision-date-plugin
  - mkdocs-minify-plugin

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/mamaofthree579-ship-it/compressive-framework-cf
  footer: "A research framework exploring compressive dynamics and particle coherence through open mathematical simulation."
