name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt || true
        pip install nbconvert jupyter

    - name: Validate and execute notebooks
      run: |
        for nb in notebooks/*.ipynb; do
          jupyter nbconvert --to html --execute "$nb" --output-dir notebooks_html || exit 0
        done
