name: Example Validation
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-notebooks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install requirements
        run: |
          pip install -r requirements.txt jupyter nbconvert
      - name: Execute example notebooks
        run: |
          jupyter nbconvert --to notebook --execute notebooks/intro_to_cf.ipynb --output executed_intro.ipynb
