name: Deploy MkDocs (with reference plots)

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs-material numpy matplotlib

      - name: Generate reference plots
        run: |
          python scripts/generate_reference_plot.py

      - name: Build & Deploy docs
        run: |
          mkdocs gh-deploy --force
