name: Notebook Validation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy matplotlib plotly sympy jupyter nbconvert

    - name: Execute Jupyter notebooks
      run: |
        mkdir -p executed_notebooks
        for nb in $(find notebooks -name "*.ipynb"); do
          echo "Running notebook: $nb"
          jupyter nbconvert --to notebook --execute "$nb" --output "executed_$(basename $nb)" --output-dir executed_notebooks
        done

    - name: Upload executed notebooks
      uses: actions/upload-artifact@v4
      with:
        name: executed-notebooks
        path: executed_notebooks/
